Vagrant.configure("2") do |config|
  config.vm.define "WhiteHacks@SG'18 CTF Easy"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "WhiteHacks@SG'18 CTF Easy"
    vb.memory = "1024"
  end
  # config.vm.box = "envimation/ubuntu-xenial"
  config.vm.box = "learningchef/ubuntu1604-desktop"
  config.vbguest.auto_update = false unless config.vbguest.nil?

  config.vm.provision "shell", path: "bootstrap.sh"
end
